BUILD_FLAGS = -W -Wall -pedantic 
CC = g++
RM = rm
OUT = *.out

all:  aubreyfernando_assignment1.out

aubreyfernando_assignment1.out: Makefile aubreyfernando_assignment1.cpp
	$(CC) $(BUILD_FLAGS) -o aubreyfernando_assignment1.out aubreyfernando_assignment1.cpp
	
clean:
	$(RM) $(OUT)
